export const PATHS = [
  {
    // not applicable for iteration 0
  },
  {
    // not applicable for iteration 1
  },
  {
    // iteration 2
    AUTH_LOGIN: 'auth/login/v2',
    AUTH_REGISTER: 'auth/register/v2',
    AUTH_LOGOUT: 'auth/logout/v1',
    CHANNEL_INVITE: 'channel/invite/v2',
    CHANNEL_DETAILS: 'channel/details/v2',
    CHANNEL_MESSAGES: 'channel/messages/v2',
    CHANNEL_JOIN: 'channel/join/v2',
    CHANNEL_ADDOWNER: 'channel/addowner/v1',
    CHANNEL_REMOVEOWNER: 'channel/removeowner/v1',
    CHANNEL_LEAVE: 'channel/leave/v1',
    CHANNELS_LIST: 'channels/list/v2',
    CHANNELS_LISTALL: 'channels/listall/v2',
    CHANNELS_CREATE: 'channels/create/v2',
    MESSAGE_SEND: 'message/send/v1',
    MESSAGE_EDIT: 'message/edit/v1',
    MESSAGE_REMOVE: 'message/remove/v1',
    DM_DETAILS: 'dm/details/v1',
    DM_LIST: 'dm/list/v1',
    DM_CREATE: 'dm/create/v1',
    DM_REMOVE: 'dm/remove/v1',
    DM_LEAVE: 'dm/leave/v1',
    DM_MESSAGES: 'dm/messages/v1',
    MESSAGE_SENDDM: 'message/senddm/v1',
    USER_PROFILE: 'user/profile/v2',
    USER_PROFILE_SETNAME: 'user/profile/setname/v1',
    USER_PROFILE_SETEMAIL: 'user/profile/setemail/v1',
    USER_PROFILE_SETHANDLE: 'user/profile/sethandle/v1',
    USERS_ALL: 'users/all/v1',
    SEARCH: 'search/v1',
    CLEAR: 'clear/v1',
  },
  {
    // iteration 3
    AUTH_LOGIN: 'auth/login/v3',
    AUTH_REGISTER: 'auth/register/v3',
    AUTH_LOGOUT: 'auth/logout/v2',
    CHANNEL_INVITE: 'channel/invite/v3',
    CHANNEL_DETAILS: 'channel/details/v3',
    CHANNEL_MESSAGES: 'channel/messages/v3',
    CHANNEL_JOIN: 'channel/join/v3',
    CHANNEL_ADDOWNER: 'channel/addowner/v2',
    CHANNEL_REMOVEOWNER: 'channel/removeowner/v2',
    CHANNEL_LEAVE: 'channel/leave/v2',
    CHANNELS_LIST: 'channels/list/v3',
    CHANNELS_LISTALL: 'channels/listall/v3',
    CHANNELS_CREATE: 'channels/create/v3',
    MESSAGE_SEND: 'message/send/v2',
    MESSAGE_EDIT: 'message/edit/v2',
    MESSAGE_REMOVE: 'message/remove/v2',
    MESSAGE_SHARE: 'message/share/v1',
    DM_DETAILS: 'dm/details/v2',
    DM_LIST: 'dm/list/v2',
    DM_CREATE: 'dm/create/v2',
    DM_REMOVE: 'dm/remove/v2',
    DM_LEAVE: 'dm/leave/v2',
    DM_MESSAGES: 'dm/messages/v2',
    MESSAGE_SENDDM: 'message/senddm/v2',
    USER_PROFILE: 'user/profile/v3',
    USER_PROFILE_SETNAME: 'user/profile/setname/v2',
    USER_PROFILE_SETEMAIL: 'user/profile/setemail/v2',
    USER_PROFILE_SETHANDLE: 'user/profile/sethandle/v2',
    USERS_ALL: 'users/all/v2',
    SEARCH: 'search/v1',
    ADMIN_USER_REMOVE: 'admin/user/remove/v1',
    ADMIN_USERPERMISSION_CHANGE: 'admin/userpermission/change/v1',
    NOTIFICATIONS_GET: 'notifications/get/v1',
    CLEAR: 'clear/v1',
    STANDUP_START: 'standup/start/v1',
    STANDUP_ACTIVE: 'standup/active/v1',
    STANDUP_SEND: 'standup/send/v1',
    AUTH_PASSWORDRESET_REQUEST: 'auth/passwordreset/request/v1',
    AUTH_PASSWORDRESET_RESET: 'auth/passwordreset/reset/v1',
    USER_STATS: 'user/stats/v1',
    USERS_STATS: 'users/stats/v1',
    USER_PROFILE_UPLOADPHOTO: 'user/profile/uploadphoto/v1',
    MESSAGE_SENDLATER: 'message/sendlater/v1',
    MESSAGE_SENDLATERDM: 'message/sendlaterdm/v1',
    MESSAGE_REACT: 'message/react/v1',
    MESSAGE_UNREACT: 'message/unreact/v1',
    MESSAGE_PIN: 'message/pin/v1',
    MESSAGE_UNPIN: 'message/unpin/v1',
  },
];
